### PR TITLE
add/edit/delete peers, ip address and online status columns

### PR DESCRIPTION
**Pull request by bryangerlach**

### CODE REVIEW

**Comment by gitondezhuts** [comment]
Brilliant, all looks good, will test later today and Merge

**Comment by bryangerlach** [comment]
It also has a button in the "all devices" section to "Claim Peer" if the device is not associated with a user already. The all devices table is only viewable by an admin user, so we might want to change the Claim Peer button (which will add the client to the currently logged in user's addressbook) to Assign Peer which would allow the admin user to choose which user's addressbook to add the client to.

**Comment by gitondezhuts** [comment]
yeah assign sounds a better plan, are you happy implementing that?

**Comment by bryangerlach** [comment]
Yeah, I will add it to this PR. I didn't think about it at first since in my use case I am the only user.

**Comment by bryangerlach** [comment]
I have made the change to allow an admin user to assign a client (any device that shows up in the admin table) to any user's addressbook. A normal user can add a client to their addressbook.

**Comment by gitondezhuts** [comment]
thats brilliant, thank you so much

**Pull request merged**
